version: '2'
services:
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=intelipost
        volumes:
             - ./postgres-data:/var/lib/postgresql/data
    gateway:
         build: auth-service/.
         depends_on:
            - db          
         ports:
            - 8080:8080
    profile-service:
         build: client/.
         depends_on:
            - gateway
         ports:
            - 8081:8081